baseURL = "/"
languageCode = "en-us"
title = "Elijah Gaytan" 
theme = "monopriv"
copyright = "Copyright © 2020" #supports html markup


[params]
about = "personal pnc site"
img = "img/me.jpg"

mattermost = "https://chatmatters.pnc.com/pnc/messages/PK21213"
email = "elijah.gaytan@pnc.com"
github = "https://github.com/chaleay"
linkedIn  = "https://www.linkedin.com/in/elijahcgaytan/"
# site meta description
metadesc = "A simple privacy oriented bootstrap hugo blog"
# site meta keywords
metakeys = "hugo, simple, minimal, bootstrap, blog"
# enable/disable disqus comments 
disqus = false 
# enable/disable google analytics 
analytics = false 
